apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: demo-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        type: allow
        operations:
          - All
        host: "*"
