export PATH=$PATH:/app:/app/kafka/bin:/data/in:/tmp/in
. .venv/bin/activate
PS1='\u@\h:\w\$ '
echo 'Welcome to Cloud Tools -- https://github.com/matgoebl/cloud-tools'
echo
if [ -d /data/ ]; then
 cd /data/
else
 cd /tmp/
fi
[ -e ./in/cloud.bashrc ] && source ./in/cloud.bashrc
